### PR TITLE
.gitmodules is using SSH protocol instead of HTTPS

### PR DESCRIPTION
**Pull request by renanmpimentel**
We have a machine which does not have a SSH key permission configured

### CODE REVIEW

**Comment by wgrafael** [comment]
+1

**Comment by guuibayer** [comment]
+1

**Comment by tonytcb** [comment]
+1

**Comment by lfdubiela** [comment]
I have the same issue here!

**Comment by rafl** [comment]
I have a machine which does not have a HTTP permission configured

**Comment by oschwald** [comment]
Thanks!

**Comment by jaisonporto** [comment]
+1

**Comment by lbozza** [comment]
@oschwald can you generate 1.2.1 tag? thank you :)

**Pull request merged**
